version: '3.9'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=base
      - MARIADB_DATABASE=core
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  app:
    image: docker.io/bitnami/laravel:8
    container_name: laravel_app
    command:
      - /bin/bash
      - -c
      - |
        php artisan migrate
        php artisan db:seed
        php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=base
      - DB_DATABASE=core
    volumes:
      - './project:/app'
    depends_on:
      mariadb:
        condition: service_healthy